name: CraftManager
main: cz.wake.manager.Main
authors: [MrWakeCZ,lilmayu]
depend: [CraftCore,CraftEconomy]
softdepend: [AdvancedEnchantments,HolographicDisplays,CommandAPI,PlaceholderAPI,ProtocolLibs]
api-version: "1.15"
version: "1.5.0"

permissions:
    craftmanager.*:
      description: Kompletni pristup k pluginu
    craftmanager.coloranvils.*:
      description: Povoleni hraci menit libovolne text itemu v kovadline
    craftmanager.vip.disenchant:
      description: Povoleni VIP k pouziti prikazu /disenchant
    craftmanager.vip.durabilitywarner:
      description: Povoleni VIP oznamenu o brzkem zniceni itemu
    craftmanager.develop:
      description: Pravo pro prikazy k testovacim ucelum
    craftmanager.particles.*:
      description: Pravo na aktivace vsech Particles v /part
    craftmanager.vip.twerking:
      description: Tweking pro VIP na SkyCloud a Vanillu
    craftmanager.chatcolor:
      description: Povoleni hraci zmeny barvy psani v /chatcolor
    craftmanager.chatcolor.at:
      description: Nastaveni zlute barvy pro AT
    craftmanager.checkfly:
      description: Kontrola pro AT, zda ma hrac zakoupene FLY na Skyblocku (nebo jinde)
    craftmanager.vip.beacon:
      description: Beacon pro HERO VIP